test:
  ip: beta.xiaohuxi.cn
  port: 443
  db_ip: 127.0.0.1
  db_port: 3308
  user_name: root
  user_pwd: Z9#b!YZK5!0OZzf^
  db_name: xhx
  redis_ip: 127.0.0.1
  redis_port: 6381
  redis_db: 0
  redis_pwd: beta-redis-0
  player_id: 1015735
  room_id: 2001090


formal:
  ip: 192.168.2.167
  port: 54321


